name: Javadoc Generation

on:
  pull_request:
  release:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Install htmldoc
        run: |
          sudo apt-get update
          sudo apt-get install htmldoc
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.13"

      - name: Generate javadoc
        run: ./gradlew javadoc

      - name: Generate PDF from javadoc
        run: |
          find ./build/docs/javadoc/io/github/onu_eccs1621_sp2025/westward | grep html$ | grep -v package > classes.txt
          htmldoc --book -f Javadoc.pdf $(< classes.txt)

      - uses: actions/upload-artifact@v4
        with:
          name: Javadoc
          path: Javadoc.pdf